### ISSUE TITLE
Fix Build/Install scripts

### ISSUE THREAD

**Issue by rubenunteregger** [Minary/Build#1]
The dev. environment is cloned from the repos in a way that build errors occure.
Reported by @Zmote 

> ... the error output of the Release Build:
> 
> Schweregrad Code Beschreibung Projekt Datei Zeile Unterdrückungszustand
> Fehler Der Befehl "if not exist "C:\Users\Zmote\Minary\..\Minary\EXTERNAL" mkdir "C:\Users\Zmote\Minary\..\Minary\EXTERNAL"
> echo xcopy /Y C:\Users\Zmote\Minary\Libs\MinaryLib\bin\Release\MinaryLib.dll C:\Users\Zmote\Minary\..\Minary\EXTERNAL
> xcopy /Y C:\Users\Zmote\Minary\Libs\MinaryLib\bin\Release\MinaryLib.dll C:\Users\Zmote\Minary\..\Minary\EXTERNAL" wurde mit dem Code 4 beendet. MinaryLib
> 

Also a little more documentation in the README could help to lower the burden to install the dev. environment.

**Comment by rubenunteregger** [comment]
@Zmote I refectored the install + build scripts after your report. If you follow the Build repository's [README](https://github.com/Minary/Build/blob/master/README.md) you should be able to download and build the whole system on your machine.

**Comment by Zmote** [comment]
@rubenunteregger Thanks for the info. I tried the new build script and it works fine as far as I can tell. Though I'm still having the APE not found error, which is why I'm still not able to use Minary, but I guess that's something I need to install separately? I'll look into it.
  
![image](https://user-images.githubusercontent.com/8780467/34574279-3853de2a-f177-11e7-9ca3-0ea13e079df0.png)

**Comment by Zmote** [comment]
I feel like the build is trying to install APE, but something is not working. Here is the build output:
What am I missing?

Load MSBuild command environment
**********************************************************************
** Visual Studio 2017 MSBuild Command Prompt
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
Check .NET directory : C:\Windows\Microsoft.NET\Framework\v4.0.30319\
Start building Libs solution [RELEASE, x86, "AnyCPU", "Any CPU"]
Bilding MinaryLib
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  MinaryLib -> C:\Users\USER_NAME\Build\Libs\MinaryLib\bin\Release\MinaryLib.dll
  Ein Unterverzeichnis oder eine Datei mit dem Namen "C:\Users\USER_NAME\Build\Libs\MinaryLib\..\..\LIBRARIES" existiert be
  reits.
  xcopy /Y  "C:\Users\USER_NAME\Build\Libs\MinaryLib\bin\Release\MinaryLib.dll" "C:\Users\USER_NAME\Build\Libs\MinaryLib\..\..\
  LIBRARIES\"
  C:\Users\USER_NAME\Build\Libs\MinaryLib\bin\Release\MinaryLib.dll
  1 Datei(en) kopiert

Bilding NativeWindowsLib
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  NativeWindowsLib -> C:\Users\USER_NAME\Build\Libs\NativeWindowsLib\bin\Release\NativeWindowsLib.dll
  Ein Unterverzeichnis oder eine Datei mit dem Namen "C:\Users\USER_NAME\Build\Libs\NativeWindowsLib\..\..\LIBRARIES" exist
  iert bereits.
  xcopy /Y  "C:\Users\USER_NAME\Build\Libs\NativeWindowsLib\bin\Release\NativeWindowsLib.dll" "C:\Users\USER_NAME\Build\Libs\Na
  tiveWindowsLib\..\..\LIBRARIES\"
  C:\Users\USER_NAME\Build\Libs\NativeWindowsLib\bin\Release\NativeWindowsLib.dll
  1 Datei(en) kopiert

Start building Tools solution [RELEASE, x86, "AnyCPU", "Any CPU"]
Building HttpReverseProxy\HttpReverseProxyLib [/t:Restore,Clean,Rebuild /p:Configuration=RELEASE,Platform="AnyCPU",WarningLevel=0 /nologo /v:m]
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  HttpReverseProxyLib -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\HttpReverseProxyLib\bin\Release\HttpReverseProxyLi
  b.dll

Building HttpReverseProxy\HttpReverseProxy [/t:Restore,Clean,Rebuild /p:Configuration=RELEASE,Platform="AnyCPU",WarningLevel=0 /nologo /v:m]
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  HttpReverseProxyLib -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\HttpReverseProxyLib\bin\Release\HttpReverseProxyLi
  b.dll
  HttpReverseProxy -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\HTTPReverseProxy\bin\Release\HttpReverseProxy.exe

Building HttpReverseProxy\SslStrip [/t:Restore,Clean,Rebuild /p:Configuration=RELEASE,Platform="AnyCPU",WarningLevel=0 /nologo /v:m]
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  HttpReverseProxyLib -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\HttpReverseProxyLib\bin\Release\HttpReverseProxyLi
  b.dll
  SslStrip -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\SslStrip\bin\Release\SslStrip.dll

Building HttpReverseProxy\ClientRequestSniffer [/t:Restore,Clean,Rebuild /p:Configuration=RELEASE,Platform="AnyCPU",WarningLevel=0 /nologo /v:m]
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  HttpReverseProxyLib -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\HttpReverseProxyLib\bin\Release\HttpReverseProxyLi
  b.dll
  ClientRequestSniffer -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\ClientRequestSniffer\bin\Release\ClientRequestSni
  ffer.dll

Building HttpReverseProxy\Weaken [/t:Restore,Clean,Rebuild /p:Configuration=RELEASE,Platform="AnyCPU",WarningLevel=0 /nologo /v:m]
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  HttpReverseProxyLib -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\HttpReverseProxyLib\bin\Release\HttpReverseProxyLi
  b.dll
  Weaken -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\Weaken\bin\Release\Weaken.dll

Building HttpReverseProxy\InjectFile [/t:Restore,Clean,Rebuild /p:Configuration=RELEASE,Platform="AnyCPU",WarningLevel=0 /nologo /v:m]
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  HttpReverseProxyLib -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\HttpReverseProxyLib\bin\Release\HttpReverseProxyLi
  b.dll
  InjectFile -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\InjectFile\bin\Release\InjectFile.dll

Building HttpReverseProxy\InjectCode [/t:Restore,Clean,Rebuild /p:Configuration=RELEASE,Platform="AnyCPU",WarningLevel=0 /nologo /v:m]
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  HttpReverseProxyLib -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\HttpReverseProxyLib\bin\Release\HttpReverseProxyLi
  b.dll
  InjectCode -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\InjectCode\bin\Release\InjectCode.dll

Building HttpReverseProxy\RequestRedirect [/t:Restore,Clean,Rebuild /p:Configuration=RELEASE,Platform="AnyCPU",WarningLevel=0 /nologo /v:m]
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  HttpReverseProxyLib -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\HttpReverseProxyLib\bin\Release\HttpReverseProxyLi
  b.dll
  RequestRedirect -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\RequestRedirect\bin\Release\RequestRedirect.dll

Building HttpReverseProxy\HostMapping [/t:Restore,Clean,Rebuild /p:Configuration=RELEASE,Platform="AnyCPU",WarningLevel=0 /nologo /v:m]
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  HttpReverseProxyLib -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\HttpReverseProxyLib\bin\Release\HttpReverseProxyLi
  b.dll
  HostMapping -> C:\Users\USER_NAME\Build\Tools\HttpReverseProxy\HostMapping\bin\Release\HostMapping.dll

Bilding Ape
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  APE.c
  ArpPoisoning.c
  Config.c
  DnsHelper.c
  DnsForge.c
  DnsPoisoning.c
  DnsResponseSpoofing.c
  getopt.c
  Interface.c
  LinkedListFirewallRules.c
  LinkedListSpoofedDnsHosts.c
LinkedListSpoofedDnsHosts.c(40): warning C4133: "=": Inkompatible Typen - von "HOSTNODE *" zu "HOSTNODE *" [C:\Users\Zm
ote\Build\Tools\Ape\Ape.vcxproj]
LinkedListSpoofedDnsHosts.c(41): warning C4133: "=": Inkompatible Typen - von "PHOSTNODE" zu "HOSTNODE *" [C:\Users\Zmo
te\Build\Tools\Ape\Ape.vcxproj]
LinkedListSpoofedDnsHosts.c(61): warning C4133: "=": Inkompatible Typen - von "HOSTNODE *" zu "HOSTNODE *" [C:\Users\Zm
ote\Build\Tools\Ape\Ape.vcxproj]
LinkedListSpoofedDnsHosts.c(62): warning C4133: "=": Inkompatible Typen - von "PHOSTNODE" zu "HOSTNODE *" [C:\Users\Zmo
te\Build\Tools\Ape\Ape.vcxproj]
LinkedListSpoofedDnsHosts.c(106): warning C4133: "=": Inkompatible Typen - von "HOSTNODE *" zu "PHOSTNODE" [C:\Users\Zm
ote\Build\Tools\Ape\Ape.vcxproj]
  LinkedListTargetSystems.c
  Logging.c
Logging.c(18): warning C4047: "=": Anzahl der Dereferenzierungen bei "HANDLE" und "int" unterschiedlich [C:\Users\USER_NAME
\Build\Tools\Ape\Ape.vcxproj]
Logging.c(19): warning C4047: "==": Anzahl der Dereferenzierungen bei "HANDLE" und "long" unterschiedlich [C:\Users\Zmo
te\Build\Tools\Ape\Ape.vcxproj]
Logging.c(25): warning C4047: "=": Anzahl der Dereferenzierungen bei "HANDLE" und "int" unterschiedlich [C:\Users\USER_NAME
\Build\Tools\Ape\Ape.vcxproj]
Logging.c(31): warning C4477: "printf": Die Formatzeichenfolge "%d" erfordert ein Argument vom Typ "int", das variadic-
Argument "2" weist aber den Typ "HANDLE" auf. [C:\Users\USER_NAME\Build\Tools\Ape\Ape.vcxproj]
Logging.c(31): warning C4477: "printf": Die Formatzeichenfolge "%d" erfordert ein Argument vom Typ "int", das variadic-
Argument "3" weist aber den Typ "HANDLE" auf. [C:\Users\USER_NAME\Build\Tools\Ape\Ape.vcxproj]
Logging.c(82): warning C4477: "printf": Die Formatzeichenfolge "%d" erfordert ein Argument vom Typ "int", das variadic-
Argument "1" weist aber den Typ "HANDLE" auf. [C:\Users\USER_NAME\Build\Tools\Ape\Ape.vcxproj]
  ModeDePoisoning.c
  ModeMitm.c
ModeMitm.c(74): warning C4133: "Funktion": Inkompatible Typen - von "FILE *" zu "const char *const " [C:\Users\USER_NAME\Bu
ild\Tools\Ape\Ape.vcxproj]
  ModePcap.c
  NetworkHelperFunctions.c
NetworkHelperFunctions.c(130): warning C4047: "!=": Anzahl der Dereferenzierungen bei "int" und "void *" unterschiedlic
h [C:\Users\USER_NAME\Build\Tools\Ape\Ape.vcxproj]
  PacketProxy.c
PacketProxy.c(128): warning C4090: "Funktion": Unterschiedliche "const"-Qualifizierer [C:\Users\USER_NAME\Build\Tools\Ape\A
pe.vcxproj]
  DnsRequestSpoofing.c
DnsRequestSpoofing.c(26): warning C4101: "errbuf": Unreferenzierte lokale Variable [C:\Users\USER_NAME\Build\Tools\Ape\Ape.
vcxproj]
  SLRE.c
  Code wird generiert.
  All 88 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  Ape.vcxproj -> C:\Users\USER_NAME\Build\Tools\Ape\RELEASE\bin\Ape.exe

Bilding Sniffer
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  Sniffer.c
  DnsParser.c
  getopt.c
  Interface.c
Interface.c(220): warning C4996: 'inet_addr': Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\USER_NAME\Build\Tools\Sniffer\Sniffer.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\winsock2.h(1830): note: Siehe Deklaration von "inet_addr"
Interface.c(224): warning C4996: 'inet_addr': Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\USER_NAME\Build\Tools\Sniffer\Sniffer.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\winsock2.h(1830): note: Siehe Deklaration von "inet_addr"
  LinkedListConnections.c
LinkedListConnections.c(325): warning C4013: "WriteOutput" undefiniert; Annahme: extern mit Rückgabetyp int [C:\Users\USER_NAME\Build\Tools\Sniffer\Sniffer.vcxproj]
  LinkedListSystems.c
  Logging.c
Logging.c(60): warning C4013: "filterException" undefiniert; Annahme: extern mit Rückgabetyp int [C:\Users\USER_NAME\Build\Tools\Sniffer\Sniffer.vcxproj]
  ModeGenericSniffer.c
  ModeMinary.c
ModeMinary.c(106): warning C4101: "payload": Unreferenzierte lokale Variable [C:\Users\USER_NAME\Build\Tools\Sniffer\Sniffer.vcxproj]
ModeMinary.c(317): warning C4047: "!=": Anzahl der Dereferenzierungen bei "int" und "void *" unterschiedlich [C:\Users\USER_NAME\Build\Tools\Sniffer\Sniffer.vcxproj]
ModeMinary.c(336): warning C4047: "!=": Anzahl der Dereferenzierungen bei "int" und "void *" unterschiedlich [C:\Users\USER_NAME\Build\Tools\Sniffer\Sniffer.vcxproj]
ModeMinary.c(347): warning C4013: "filterException" undefiniert; Annahme: extern mit Rückgabetyp int [C:\Users\USER_NAME\Build\Tools\Sniffer\Sniffer.vcxproj]
  NetworkFunctions.c
  Code wird generiert.
  All 37 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  Sniffer.vcxproj -> C:\Users\USER_NAME\Build\Tools\Sniffer\RELEASE\bin\Sniffer.exe

Start building AttackServices solution [RELEASE, x86, "AnyCPU", "Any CPU"]
Bilding AttackServices
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  xcopy /Y "C:\Users\USER_NAME\Build\AttackServices\ArpPoisoning\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\AttackServices\ArpPoisoning\LIBRARIES\"
  C:\Users\USER_NAME\Build\AttackServices\ArpPoisoning\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  ArpPoisoning -> C:\Users\USER_NAME\Build\AttackServices\ArpPoisoning\bin\Release\AS_ArpPoisoning.dll
  Ein Unterverzeichnis oder eine Datei mit dem Namen "C:\Users\USER_NAME\Build\AttackServices\ArpPoisoning\..\..\LIBRARIES" existiert bereits.
  xcopy /Y  "C:\Users\USER_NAME\Build\AttackServices\ArpPoisoning\bin\Release\AS_ArpPoisoning.dll" "C:\Users\USER_NAME\Build\AttackServices\ArpPoisoning\..\..\LIBRARIES\"
  C:\Users\USER_NAME\Build\AttackServices\ArpPoisoning\bin\Release\AS_ArpPoisoning.dll
  1 Datei(en) kopiert

Bilding ArpSniffer
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  xcopy /Y "C:\Users\USER_NAME\Build\AttackServices\Sniffer\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\AttackServices\Sniffer\LIBRARIES\"
  C:\Users\USER_NAME\Build\AttackServices\Sniffer\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  Sniffer -> C:\Users\USER_NAME\Build\AttackServices\Sniffer\bin\Release\AS_Sniffer.dll
  Ein Unterverzeichnis oder eine Datei mit dem Namen "C:\Users\USER_NAME\Build\AttackServices\Sniffer\..\..\LIBRARIES" existiert bereits.
  xcopy /Y  "C:\Users\USER_NAME\Build\AttackServices\Sniffer\bin\Release\AS_Sniffer.dll" "C:\Users\USER_NAME\Build\AttackServices\Sniffer\..\..\LIBRARIES\"
  C:\Users\USER_NAME\Build\AttackServices\Sniffer\bin\Release\AS_Sniffer.dll
  1 Datei(en) kopiert

Bilding HttpReverseProxy
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  xcopy /Y "C:\Users\USER_NAME\Build\AttackServices\HttpReverseProxy\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\AttackServices\HttpReverseProxy\LIBRARIES\"
  C:\Users\USER_NAME\Build\AttackServices\HttpReverseProxy\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  xcopy /Y "C:\Users\USER_NAME\Build\AttackServices\HttpReverseProxy\..\..\LIBRARIES\NativeWindowsLib.dll"  "C:\Users\USER_NAME\Build\AttackServices\HttpReverseProxy\LIBRARIES\"
  C:\Users\USER_NAME\Build\AttackServices\HttpReverseProxy\..\..\LIBRARIES\NativeWindowsLib.dll
  1 Datei(en) kopiert
  HttpReverseProxy -> C:\Users\USER_NAME\Build\AttackServices\HttpReverseProxy\bin\Release\AS_HttpReverseProxy.dll
  Ein Unterverzeichnis oder eine Datei mit dem Namen "C:\Users\USER_NAME\Build\AttackServices\HttpReverseProxy\..\..\LIBRARIES" existiert bereits.
  xcopy /Y  "C:\Users\USER_NAME\Build\AttackServices\HttpReverseProxy\bin\Release\AS_HttpReverseProxy.dll" "C:\Users\USER_NAME\Build\AttackServices\HttpReverseProxy\..\..\LIBRARIES\"
  C:\Users\USER_NAME\Build\AttackServices\HttpReverseProxy\bin\Release\AS_HttpReverseProxy.dll
  1 Datei(en) kopiert

Start building Minary plugins [RELEASE, x86, "AnyCPU", "Any CPU"]
Building Plugins solution [/t:Restore,Clean,Rebuild /p:Configuration=RELEASE,Platform="Any CPU",WarningLevel=0 /nologo /v:m]
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  xcopy /Y "C:\Users\USER_NAME\Build\Plugins\Plugin_BrowserExploitKit\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Plugins\Plugin_BrowserExploitKit\LIBRARIES\"
  C:\Users\USER_NAME\Build\Plugins\Plugin_BrowserExploitKit\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  Plugin_BrowserExploitKit -> C:\Users\USER_NAME\Build\Plugins\Plugin_BrowserExploitKit\bin\Release\Plugin_BrowserExploitKit.dll
  xcopy /Y "C:\Users\USER_NAME\Build\Plugins\Plugin_DnsPoisoning\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Plugins\Plugin_DnsPoisoning\LIBRARIES\"
  C:\Users\USER_NAME\Build\Plugins\Plugin_DnsPoisoning\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  Plugin_DnsPoisoning -> C:\Users\USER_NAME\Build\Plugins\Plugin_DnsPoisoning\bin\Release\Plugin_DnsPoisoning.dll
  xcopy /Y "C:\Users\USER_NAME\Build\Plugins\Plugin_DnsRequests\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Plugins\Plugin_DnsRequests\LIBRARIES\"
  C:\Users\USER_NAME\Build\Plugins\Plugin_DnsRequests\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  Plugin_DnsRequests -> C:\Users\USER_NAME\Build\Plugins\Plugin_DnsRequests\bin\Release\Plugin_DnsRequests.dll
  xcopy /Y "C:\Users\USER_NAME\Build\Plugins\Plugin_Firewall\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Plugins\Plugin_Firewall\LIBRARIES\"
  C:\Users\USER_NAME\Build\Plugins\Plugin_Firewall\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  Plugin_Firewall -> C:\Users\USER_NAME\Build\Plugins\Plugin_Firewall\bin\Release\Plugin_Firewall.dll
  xcopy /Y "C:\Users\USER_NAME\Build\Plugins\Plugin_HttpAccounts\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Plugins\Plugin_HttpAccounts\LIBRARIES\"
  C:\Users\USER_NAME\Build\Plugins\Plugin_HttpAccounts\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  Plugin_HttpAccounts -> C:\Users\USER_NAME\Build\Plugins\Plugin_HttpAccounts\bin\Release\Plugin_HttpAccounts.dll
  xcopy /Y "C:\Users\USER_NAME\Build\Plugins\Plugin_HttpHostMapping\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Plugins\Plugin_HttpHostMapping\LIBRARIES\"
  C:\Users\USER_NAME\Build\Plugins\Plugin_HttpHostMapping\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  Plugin_HttpHostMapping -> C:\Users\USER_NAME\Build\Plugins\Plugin_HttpHostMapping\bin\Release\Plugin_HttpHostMapping.dll
  xcopy /Y "C:\Users\USER_NAME\Build\Plugins\Plugin_HttpInjectCode\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Plugins\Plugin_HttpInjectCode\LIBRARIES\"
  C:\Users\USER_NAME\Build\Plugins\Plugin_HttpInjectCode\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  Plugin_HttpInjectCode -> C:\Users\USER_NAME\Build\Plugins\Plugin_HttpInjectCode\bin\Release\Plugin_HttpInjectCode.dll
  xcopy /Y "C:\Users\USER_NAME\Build\Plugins\Plugin_HttpInjectFile\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Plugins\Plugin_HttpInjectFile\LIBRARIES\"
  C:\Users\USER_NAME\Build\Plugins\Plugin_HttpInjectFile\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  Plugin_HttpInjectFile -> C:\Users\USER_NAME\Build\Plugins\Plugin_HttpInjectFile\bin\Release\Plugin_HttpInjectFile.dll
  xcopy /Y "C:\Users\USER_NAME\Build\Plugins\Plugin_HttpRequestRedirect\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Plugins\Plugin_HttpRequestRedirect\LIBRARIES\"
  C:\Users\USER_NAME\Build\Plugins\Plugin_HttpRequestRedirect\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  Plugin_HttpRequestRedirect -> C:\Users\USER_NAME\Build\Plugins\Plugin_HttpRequestRedirect\bin\Release\Plugin_HttpRequestRedirect.dll
  xcopy /Y "C:\Users\USER_NAME\Build\Plugins\Plugin_HttpRequests\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Plugins\Plugin_HttpRequests\LIBRARIES\"
  C:\Users\USER_NAME\Build\Plugins\Plugin_HttpRequests\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3245: Dieser Verweis konnte nicht aufgelöst werden. Die "Interop.SHDocVw"-Assembly wurde nicht ge
funden. Stellen Sie sicher, dass die Assembly auf dem Datenträger vorhanden ist. Falls dieser Verweis im Code erforderlich ist, können Kompilierungsfehler auftreten. [C:\Users\USER_NAME\Build\Plugins\Plugin_HttpRequests\Plugin_HttpRequests.
csproj]
  Plugin_HttpRequests -> C:\Users\USER_NAME\Build\Plugins\Plugin_HttpRequests\bin\Release\Plugin_HttpRequests.dll
  xcopy /Y "C:\Users\USER_NAME\Build\Plugins\Plugin_Sessions\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Plugins\Plugin_Sessions\LIBRARIES\"
  C:\Users\USER_NAME\Build\Plugins\Plugin_Sessions\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  Plugin_Sessions -> C:\Users\USER_NAME\Build\Plugins\Plugin_Sessions\bin\Release\Plugin_Sessions.dll
  xcopy /Y "C:\Users\USER_NAME\Build\Plugins\Plugin_SslStrip\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Plugins\Plugin_SslStrip\LIBRARIES\"
  C:\Users\USER_NAME\Build\Plugins\Plugin_SslStrip\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  Plugin_SslStrip -> C:\Users\USER_NAME\Build\Plugins\Plugin_SslStrip\bin\Release\Plugin_SslStrip.dll
  xcopy /Y "C:\Users\USER_NAME\Build\Plugins\Plugin_Systems\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Plugins\Plugin_Systems\LIBRARIES\"
  C:\Users\USER_NAME\Build\Plugins\Plugin_Systems\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  Plugin_Systems -> C:\Users\USER_NAME\Build\Plugins\Plugin_Systems\bin\Release\Plugin_Systems.dll
Start building Minary plugins [RELEASE, x86, "AnyCPU", "Any CPU"]
Bilding Minary\Minary [/t:Restore,Clean,Rebuild  /nologo /v:m]
  Keine Aktion erforderlich. Keines der angegebenen Projekte enthält wiederherzustellende Pakete.
  NuGet-Pakete werden wiederhergestellt...
  Damit verhindert wird, dass NuGet Pakete während des Buildvorgangs herunterlädt, öffnen Sie das Dialogfeld "Optionen" von Visual Studio, klicken Sie auf den Knoten "Paket-Manager", und deaktivieren Sie dann "Allow NuGet to download mi
  ssing packages".
  Feeds used:
    C:\Users\USER_NAME\.nuget\packages\
    https://api.nuget.org/v3/index.json

  Alle in "C:\Users\USER_NAME\Build\Minary\Minary\packages.config" aufgeführten Pakete sind bereits installiert.
  xcopy /Y "C:\Users\USER_NAME\Build\Minary\Minary\..\..\LIBRARIES\MinaryLib.dll"  "C:\Users\USER_NAME\Build\Minary\Minary\LIBRARIES\"
  C:\Users\USER_NAME\Build\Minary\Minary\..\..\LIBRARIES\MinaryLib.dll
  1 Datei(en) kopiert
  xcopy /Y "C:\Users\USER_NAME\Build\Minary\Minary\..\..\LIBRARIES\NativeWindowsLib.dll"  "C:\Users\USER_NAME\Build\Minary\Minary\LIBRARIES\"
  C:\Users\USER_NAME\Build\Minary\Minary\..\..\LIBRARIES\NativeWindowsLib.dll
  1 Datei(en) kopiert
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3270: Konflikt zwischen der Prozessorarchitektur des Projekts "MSIL", das erstellt wird, und der
Prozessorarchitektur des Verweises, "PcapDotNet.Core, Version=0.10.0.20632, Culture=neutral, PublicKeyToken=4b6f3e583145a652, processorArchitecture=x86", "x86". Dieser Konflikt kann zu Laufzeitfehlern führen. Ändern Sie ggf. mithilfe de
s Konfigurations-Managers die als Ziel angegebene Prozessorarchitektur Ihres Projekts so, dass die Prozessorarchitekturen zwischen Ihrem Projekt und den Verweisen ausgerichtet werden, oder wählen Sie eine Abhängigkeit von Verweisen mit
einer Prozessorarchitektur, die der als Ziel angegebene Prozessorarchitektur Ihres Projekts entspricht. [C:\Users\USER_NAME\Build\Minary\Minary\Minary.csproj]
  Minary -> C:\Users\USER_NAME\Build\Minary\Minary\bin\Release\Minary.exe

**Comment by rubenunteregger** [comment]
@Zmote : Step one (FETCH) and two (COMPILE) were passed successfully according your output. Just to have it asked: Did you BUILD it as described in the [README](https://github.com/Minary/Build/blob/master/README.md#building-new-release-package)?

**Comment by Zmote** [comment]
@rubenunteregger Yep, I even got the Tools error you described, built it separately and rebuilt the whole thing, without complaints. The app is starting, but when I try to spoof, I get those errors. The APE... that should be built during installation right? It's not something I need to get seperately?

**Comment by rubenunteregger** [comment]
@Zmote FETCH, COMPILE and PACKAGE are meant to be single step instruction. The COMPILE/fclp issue is an exception which I hopefully can fix in a later release. There is nothing extra you're supposed to do to COMPILE the projects. So you've done everything right.

Can you please send me the PACKAGE.bat output and a recursive listing of the BUILDS\RELEASE\VERSION output directory?

**Comment by Zmote** [comment]
@rubenunteregger Alright, I got it working after redoing the PACKAGE.bat (first time it ended with an error, the second time it said it was already built)... but to be more exact, starting the Minary binary from BUILDS/RELEASE/MINARY was more successful, ie. no errors, spoofing was possible etc., the way it's supposed to be working I assume, previously I was starting it from the Minary/bin folder, which I guess didn't find the necessary .dll's in that folder. Thanks for the help!

**Comment by rubenunteregger** [comment]
@Zmote That's correct. The solutions/projects are relevant for programming but not for actually running minary. That's where the COMPILE/BUILD scripts come into play. The assembled Minary environmen is located in BUILDS/[RELEASE|DEBUG]/VERSION.
Cool! Thanks for your feedback!
